/**
 * Seed script — inserts 20 sample books into the library database.
 * Usage: node seed_books.js
 */
require('dotenv').config();
const mysql = require('mysql2/promise');

const books = [
  {
    title: 'Introduction to Information Technology',
    author: 'Efraim Turban',
    co_author: 'Linda Volonino',
    type: 'Book',
    publisher: 'McGraw-Hill Education',
    place: 'New York',
    date_published: '2021',
    category: 'Information Technology',
    pages: '612',
    isbn: '978-0-07-352285-2',
    accession_no: 'ACC-001',
    call_no: 'QA76.T87 2021',
    barcode: 'BK-000001',
    location: 'Main Shelf A1',
    circulation_type: 'Loanable',
    price: 1850.00,
    copies_available: 3,
  },
  {
    title: 'Fundamentals of Programming: C and C++',
    author: 'Richard L. Halterman',
    co_author: '',
    type: 'Book',
    publisher: 'Southern Adventist University Press',
    place: 'Tennessee',
    date_published: '2019',
    category: 'Programming',
    pages: '428',
    isbn: '978-1-4920-7339-0',
    accession_no: 'ACC-002',
    call_no: 'QA76.73.C H35 2019',
    barcode: 'BK-000002',
    location: 'Main Shelf A1',
    circulation_type: 'Loanable',
    price: 1200.00,
    copies_available: 2,
  },
  {
    title: 'Calculus: Early Transcendentals',
    author: 'James Stewart',
    co_author: 'Daniel Clegg',
    type: 'Book',
    publisher: 'Cengage Learning',
    place: 'Boston',
    date_published: '2020',
    category: 'Mathematics',
    pages: '1156',
    isbn: '978-1-337-61392-7',
    accession_no: 'ACC-003',
    call_no: 'QA303.2.S74 2020',
    barcode: 'BK-000003',
    location: 'Main Shelf B2',
    circulation_type: 'Loanable',
    price: 2400.00,
    copies_available: 4,
  },
  {
    title: 'Philippine History: A Comprehensive Study',
    author: 'Milagros Guerrero',
    co_author: 'Emmanuel Encarnacion',
    type: 'Book',
    publisher: 'Rex Book Store',
    place: 'Manila',
    date_published: '2018',
    category: 'Philippine History',
    pages: '380',
    isbn: '978-971-23-8765-4',
    accession_no: 'ACC-004',
    call_no: 'DS661.G84 2018',
    barcode: 'BK-000004',
    location: 'Main Shelf C3',
    circulation_type: 'Loanable',
    price: 950.00,
    copies_available: 5,
  },
  {
    title: 'Biology: The Science of Life',
    author: 'Robert A. Wallace',
    co_author: 'Gerald P. Sanders',
    type: 'Book',
    publisher: 'HarperCollins',
    place: 'New York',
    date_published: '2020',
    category: 'Biology',
    pages: '870',
    isbn: '978-0-06-046182-1',
    accession_no: 'ACC-005',
    call_no: 'QH307.2.W35 2020',
    barcode: 'BK-000005',
    location: 'Main Shelf B3',
    circulation_type: 'Loanable',
    price: 1750.00,
    copies_available: 3,
  },
  {
    title: 'Principles of Economics',
    author: 'N. Gregory Mankiw',
    co_author: '',
    type: 'Book',
    publisher: 'Cengage Learning',
    place: 'Mason, Ohio',
    date_published: '2021',
    category: 'Economics',
    pages: '888',
    isbn: '978-0-357-03831-4',
    accession_no: 'ACC-006',
    call_no: 'HB171.5.M36 2021',
    barcode: 'BK-000006',
    location: 'Main Shelf D1',
    circulation_type: 'Loanable',
    price: 2200.00,
    copies_available: 2,
  },
  {
    title: 'Noli Me Tangere',
    author: 'Jose Rizal',
    co_author: '',
    type: 'Book',
    publisher: 'Bookmark Inc.',
    place: 'Makati',
    date_published: '2017',
    category: 'Filipino Literature',
    pages: '396',
    isbn: '978-971-569-600-3',
    accession_no: 'ACC-007',
    call_no: 'PQ8897.R59 N6 2017',
    barcode: 'BK-000007',
    location: 'Filipino Works Shelf',
    circulation_type: 'Loanable',
    price: 450.00,
    copies_available: 8,
  },
  {
    title: 'El Filibusterismo',
    author: 'Jose Rizal',
    co_author: '',
    type: 'Book',
    publisher: 'Bookmark Inc.',
    place: 'Makati',
    date_published: '2017',
    category: 'Filipino Literature',
    pages: '348',
    isbn: '978-971-569-601-0',
    accession_no: 'ACC-008',
    call_no: 'PQ8897.R59 E4 2017',
    barcode: 'BK-000008',
    location: 'Filipino Works Shelf',
    circulation_type: 'Loanable',
    price: 450.00,
    copies_available: 7,
  },
  {
    title: 'General Chemistry',
    author: 'Darrell D. Ebbing',
    co_author: 'Steven D. Gammon',
    type: 'Book',
    publisher: 'Cengage Learning',
    place: 'Boston',
    date_published: '2022',
    category: 'Chemistry',
    pages: '1120',
    isbn: '978-0-357-36624-1',
    accession_no: 'ACC-009',
    call_no: 'QD33.2.E22 2022',
    barcode: 'BK-000009',
    location: 'Main Shelf B1',
    circulation_type: 'Loanable',
    price: 2600.00,
    copies_available: 3,
  },
  {
    title: 'Introduction to Psychology',
    author: 'James W. Kalat',
    co_author: '',
    type: 'Book',
    publisher: 'Cengage Learning',
    place: 'Belmont, CA',
    date_published: '2019',
    category: 'Psychology',
    pages: '628',
    isbn: '978-1-337-56528-9',
    accession_no: 'ACC-010',
    call_no: 'BF121.K35 2019',
    barcode: 'BK-000010',
    location: 'Main Shelf D2',
    circulation_type: 'Loanable',
    price: 1900.00,
    copies_available: 2,
  },
  {
    title: 'Database Management Systems',
    author: 'Ramez Elmasri',
    co_author: 'Sham Navathe',
    type: 'Book',
    publisher: 'Pearson Education',
    place: 'Hoboken, NJ',
    date_published: '2020',
    category: 'Information Technology',
    pages: '1034',
    isbn: '978-0-13-468859-5',
    accession_no: 'ACC-011',
    call_no: 'QA76.9.D3 E45 2020',
    barcode: 'BK-000011',
    location: 'Main Shelf A2',
    circulation_type: 'Loanable',
    price: 2800.00,
    copies_available: 2,
  },
  {
    title: 'Principles of Marketing',
    author: 'Philip Kotler',
    co_author: 'Gary Armstrong',
    type: 'Book',
    publisher: 'Pearson Education',
    place: 'Hoboken, NJ',
    date_published: '2021',
    category: 'Business & Management',
    pages: '752',
    isbn: '978-0-13-671232-1',
    accession_no: 'ACC-012',
    call_no: 'HF5415.K636 2021',
    barcode: 'BK-000012',
    location: 'Main Shelf D1',
    circulation_type: 'Loanable',
    price: 2100.00,
    copies_available: 3,
  },
  {
    title: 'Fundamentals of Nursing: Concepts and Application',
    author: 'Barbara Kozier',
    co_author: 'Glenora Erb',
    type: 'Book',
    publisher: 'Pearson Education',
    place: 'Upper Saddle River, NJ',
    date_published: '2021',
    category: 'Nursing',
    pages: '1840',
    isbn: '978-0-13-558016-5',
    accession_no: 'ACC-013',
    call_no: 'RT41.K69 2021',
    barcode: 'BK-000013',
    location: 'Health Sciences Shelf',
    circulation_type: 'Loanable',
    price: 3200.00,
    copies_available: 2,
  },
  {
    title: 'Environmental Science: Toward a Sustainable Future',
    author: 'Richard T. Wright',
    co_author: 'Dorothy F. Boorse',
    type: 'Book',
    publisher: 'Pearson Education',
    place: 'Boston',
    date_published: '2020',
    category: 'Environmental Science',
    pages: '704',
    isbn: '978-0-13-449637-0',
    accession_no: 'ACC-014',
    call_no: 'GE105.W75 2020',
    barcode: 'BK-000014',
    location: 'Main Shelf B4',
    circulation_type: 'Loanable',
    price: 1850.00,
    copies_available: 3,
  },
  {
    title: 'The Art of Teaching',
    author: 'Gilbert Highet',
    co_author: '',
    type: 'Book',
    publisher: 'Vintage Books',
    place: 'New York',
    date_published: '2018',
    category: 'Education',
    pages: '291',
    isbn: '978-0-394-70121-5',
    accession_no: 'ACC-015',
    call_no: 'LB1025.H5 2018',
    barcode: 'BK-000015',
    location: 'Education Shelf',
    circulation_type: 'Loanable',
    price: 780.00,
    copies_available: 4,
  },
  {
    title: 'Bohol: A Cultural Heritage Guide',
    author: 'Carlos V. Celdran',
    co_author: '',
    type: 'Book',
    publisher: 'Anvil Publishing',
    place: 'Mandaluyong',
    date_published: '2019',
    category: 'Local Studies',
    pages: '215',
    isbn: '978-971-27-3356-7',
    accession_no: 'ACC-016',
    call_no: 'DS688.B65 C45 2019',
    barcode: 'BK-000016',
    location: 'Filipiniana Shelf',
    circulation_type: 'Reference',
    price: 620.00,
    copies_available: 2,
  },
  {
    title: 'Technical Communication: Principles and Practice',
    author: 'Meenakshi Raman',
    co_author: 'Sangeeta Sharma',
    type: 'Book',
    publisher: 'Oxford University Press',
    place: 'New Delhi',
    date_published: '2021',
    category: 'Communication',
    pages: '415',
    isbn: '978-0-19-947490-3',
    accession_no: 'ACC-017',
    call_no: 'T10.5.R36 2021',
    barcode: 'BK-000017',
    location: 'Main Shelf C1',
    circulation_type: 'Loanable',
    price: 1100.00,
    copies_available: 5,
  },
  {
    title: 'Agricultural Science: Foundations and Applications',
    author: 'Ray V. Herren',
    co_author: '',
    type: 'Book',
    publisher: 'Delmar Cengage Learning',
    place: 'Clifton Park, NY',
    date_published: '2020',
    category: 'Agriculture',
    pages: '592',
    isbn: '978-1-4354-8815-5',
    accession_no: 'ACC-018',
    call_no: 'S521.H47 2020',
    barcode: 'BK-000018',
    location: 'Agriculture Shelf',
    circulation_type: 'Loanable',
    price: 1650.00,
    copies_available: 3,
  },
  {
    title: 'Web Development and Design Foundations with HTML5',
    author: 'Terry Felke-Morris',
    co_author: '',
    type: 'Book',
    publisher: 'Pearson Education',
    place: 'Hoboken, NJ',
    date_published: '2022',
    category: 'Information Technology',
    pages: '590',
    isbn: '978-0-13-758994-3',
    accession_no: 'ACC-019',
    call_no: 'TK5105.888.F45 2022',
    barcode: 'BK-000019',
    location: 'Main Shelf A3',
    circulation_type: 'Loanable',
    price: 2050.00,
    copies_available: 2,
  },
  {
    title: 'Rizal Without the Overcoat',
    author: 'Ambeth R. Ocampo',
    co_author: '',
    type: 'Book',
    publisher: 'Anvil Publishing',
    place: 'Mandaluyong',
    date_published: '2020',
    category: 'Filipino Literature',
    pages: '224',
    isbn: '978-971-27-2980-5',
    accession_no: 'ACC-020',
    call_no: 'CT1930.R59 O23 2020',
    barcode: 'BK-000020',
    location: 'Filipiniana Shelf',
    circulation_type: 'Loanable',
    price: 420.00,
    copies_available: 6,
  },
];

async function seed() {
  const pool = await mysql.createPool({
    host:     process.env.DB_HOST     || '127.0.0.1',
    port:     process.env.DB_PORT     || 3306,
    user:     process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    waitForConnections: true,
    connectionLimit: 5,
  });

  console.log('Connected to MySQL. Seeding 20 sample books...\n');

  let inserted = 0;
  let skipped  = 0;

  for (const book of books) {
    try {
      await pool.query(
        `INSERT INTO books
          (title, author, co_author, type, publisher, place, date_published,
           category, pages, isbn, accession_no, call_no, barcode, location,
           circulation_type, price, copies_available)
         VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
        [
          book.title, book.author, book.co_author || null, book.type,
          book.publisher, book.place, book.date_published,
          book.category, book.pages, book.isbn,
          book.accession_no, book.call_no, book.barcode, book.location,
          book.circulation_type, book.price, book.copies_available,
        ]
      );
      console.log(`  ✓ [${book.accession_no}] ${book.title}`);
      inserted++;
    } catch (err) {
      if (err.code === 'ER_DUP_ENTRY') {
        console.log(`  ↷ [${book.accession_no}] ${book.title} — already exists, skipped`);
        skipped++;
      } else {
        console.error(`  ✗ [${book.accession_no}] ${book.title} — ERROR: ${err.message}`);
      }
    }
  }

  console.log(`\nDone! ${inserted} inserted, ${skipped} skipped.`);
  await pool.end();
}

seed().catch((err) => {
  console.error('Seed failed:', err.message);
  process.exit(1);
});
